### ISSUE TITLE
After update to version 2.3.0 createContact attributes must now be object in Typescript

### ISSUE THREAD

**Issue by xelaz** [getbrevo/brevo-node#55]
```typescript

const clientBrevo = new ContactsApi();

clientBrevo.setApiKey(
  ContactsApiApiKeys.apiKey,
  client.options.brevo.apiKey
);

await clientBrevo.createContact({
  email,
  attributes: {
    VORNAME: firstName,
    NACHNAME: lastName,
    FIRMA: company,
  },
  listIds: client.options.brevo.listId
    .split(',')
    .map((id) => parseInt(id, 10)),
  updateEnabled: true,
});
```

After update to version 2.3.0 TypeScript get Error on createBrevo

TS2322: Type string is not assignable to type object

In version 2.30
```
/**
* Pass the set of attributes and their values. These attributes must be present in your Brevo account. For eg. 
{'FNAME':'Elly', 'LNAME':'Roger', 'COUNTRIES':['India','China']}
*/
'attributes'?: { [key: string]: object; };
```

In version 2.2.0 it was as object
```
/**
* Pass the set of attributes and their values. The attribute\'s parameter should be passed in capital letter while creating a contact. Values that don\'t match the attribute type (e.g. text or string in a date attribute) will be ignored.These attributes must be present in your Brevo account. For eg. {\"FNAME\":\"Elly\", \"LNAME\":\"Roger\"}
*/
'attributes'?: object;
```

How i can pass obejct if i have string or string[]

And i can't  use this alias and why:
attributes: {
    VORNAME: firstName as object,
    NACHNAME: lastName as any,
    FIRMA: company,
  },

How to Fix:
'attributes'?: { [key: string]: string | string[]; };

or with number or boolean what can be set as attribute.

**Comment by Segfaultd** [comment]
Same issue here

**Comment by Flamenate** [comment]
Safest way to deal with the error in my opinion is with `//@ts-expect-error`.
It'll throw an error once they update the types.

**Comment by zsombor-somogyi** [comment]
I followed the type definition and documentation in readme file, and that not work at all.
After making an assumption after seeing the 2 examples different, I tried with this, and worked.
```ts
  contact.attributes = {
    SIGNUP_DATE : created.toISOString() as unknown as object,
    FUNNEL_TYPE : (hiddenFields?.funnel_type ?? '') as unknown as object,
    CHANNEL : (hiddenFields?.channel ?? '') as unknown as object
  };
```
Needs to fix the type definition and the readme file.

**Comment by aloisklink** [comment]
I had a look at the OpenAPI spec in https://api.brevo.com/v3/swagger_definition_v3.yml and the issue is already fixed there and states that attributes can only be a `number`, `string`, `boolean`, or `string[]`.

So I suspect once @shubhamUpadhyayInBlue publishes a new version of this package from the latest OpenAPI spec, the issue would be fixed.

```yaml
    createContact:
      type: object
      properties:
        # -- snip --
        attributes:
          type: object
          additionalProperties:
            oneOf:
              - type: number
              - type: string
              - type: boolean
              - type: array
                items:
                  type: string
          description: |
            Pass the set of attributes and their values. The attribute's parameter should be passed in capital letter while creating a contact. Values that don't match the attribute type (e.g. text or string in a date attribute) will be ignored. **These attributes must be present in your Brevo account.**. For eg:
            **{"FNAME":"Elly", "LNAME":"Roger", "COUNTRIES":["India","China"]}**
          example:
            FNAME: Elly
            LNAME: Roger
            COUNTRIES: [India,China]
```
